// src/lib/components/AICommandSuggestions.svelte
<script lang="ts">
	import { cn } from '$lib/utils.js';
	import { createEventDispatcher, onMount } from 'svelte';
	import { writable } from 'svelte/store';
	import { fly, fade } from 'svelte/transition';

	interface CommandSuggestion {
		id: string;
		command: string;
		description: string;
		category: 'system' | 'development' | 'network' | 'file' | 'process' | 'ai';
		confidence: number;
		usage: string;
		parameters?: string[];
		examples?: string[];
	}

	interface Props {
		query: string;
		suggestions?: CommandSuggestion[];
		maxSuggestions?: number;
		showConfidence?: boolean;
		showCategories?: boolean;
		theme?: 'terminal' | 'cyberpunk' | 'neural';
		aiMode?: boolean;
		class?: string;
	}

	const {
		query = '',
		suggestions = [],
		maxSuggestions = 6,
		showConfidence = true,
		showCategories = true,
		theme = 'terminal',
		aiMode = true,
		class: className = ''
	}: Props = $props();

	const dispatch = createEventDispatcher();

	// AI-generated suggestions based on query
	const aiSuggestions = writable<CommandSuggestion[]>([]);
	let selectedIndex = $state(-1);
	let isThinking = $state(false);

	// Default command database
	const defaultCommands: CommandSuggestion[] = [
		{
			id: 'ls',
			command: 'ls',
			description: 'List directory contents with detailed information',
			category: 'file',
			confidence: 0.95,
			usage: 'ls [options] [directory]',
			parameters: ['-l', '-a', '-h', '-t', '-r'],
			examples: ['ls -la', 'ls -lh /home', 'ls -lt']
		},
		{
			id: 'grep',
			command: 'grep',
			description: 'Search text patterns in files',
			category: 'file',
			confidence: 0.92,
			usage: 'grep [options] pattern [file...]',
			parameters: ['-r', '-i', '-n', '-v', '-E'],
			examples: ['grep -r "function" .', 'grep -n "error" log.txt']
		},
		{
			id: 'git-status',
			command: 'git status',
			description: 'Show working tree status and staged changes',
			category: 'development',
			confidence: 0.98,
			usage: 'git status [options]',
			parameters: ['-s', '--porcelain', '--branch'],
			examples: ['git status', 'git status -s']
		},
		{
			id: 'npm-install',
			command: 'npm install',
			description: 'Install dependencies from package.json',
			category: 'development',
			confidence: 0.94,
			usage: 'npm install [package] [options]',
			parameters: ['--save', '--save-dev', '--global', '--force'],
			examples: ['npm install', 'npm install lodash --save']
		},
		{
			id: 'curl',
			command: 'curl',
			description: 'Transfer data from or to network servers',
			category: 'network',
			confidence: 0.89,
			usage: 'curl [options] [URL...]',
			parameters: ['-X', '-H', '-d', '-o', '-L'],
			examples: ['curl -X GET https://api.example.com', 'curl -H "Content-Type: application/json"']
		},
		{
			id: 'docker-ps',
			command: 'docker ps',
			description: 'List running Docker containers',
			category: 'system',
			confidence: 0.93,
			usage: 'docker ps [options]',
			parameters: ['-a', '--format', '--filter'],
			examples: ['docker ps', 'docker ps -a']
		},
		{
			id: 'tail',
			command: 'tail',
			description: 'Display last lines of files in real-time',
			category: 'file',
			confidence: 0.91,
			usage: 'tail [options] [file...]',
			parameters: ['-f', '-n', '-c'],
			examples: ['tail -f /var/log/syslog', 'tail -n 50 error.log']
		},
		{
			id: 'htop',
			command: 'htop',
			description: 'Interactive process viewer and system monitor',
			category: 'process',
			confidence: 0.87,
			usage: 'htop [options]',
			parameters: ['-d', '-u', '--sort-key'],
			examples: ['htop', 'htop -d 5']
		}
	];

	// Theme configurations
	const themeConfig = {
		terminal: {
			bg: 'bg-terminal-bg/95 border-terminal-green/30',
			text: 'text-terminal-green',
			accent: 'text-terminal-cyan',
			muted: 'text-terminal-green/60',
			selected: 'bg-terminal-green/20',
			category: 'text-terminal-blue'
		},
		cyberpunk: {
			bg: 'bg-purple-950/95 border-pink-500/30',
			text: 'text-pink-300',
			accent: 'text-cyan-300',
			muted: 'text-pink-300/60',
			selected: 'bg-pink-500/20',
			category: 'text-purple-300'
		},
		neural: {
			bg: 'bg-slate-900/95 border-blue-400/30',
			text: 'text-blue-300',
			accent: 'text-purple-300',
			muted: 'text-blue-300/60',
			selected: 'bg-blue-500/20',
			category: 'text-indigo-300'
		}
	};

	const currentTheme = themeConfig[theme];

	// Category icons and colors
	const categoryConfig = {
		system: { icon: '⚙️', color: 'text-blue-400' },
		development: { icon: '💻', color: 'text-green-400' },
		network: { icon: '🌐', color: 'text-purple-400' },
		file: { icon: '📁', color: 'text-yellow-400' },
		process: { icon: '⚡', color: 'text-orange-400' },
		ai: { icon: '🤖', color: 'text-cyan-400' }
	};

	// AI thinking simulation
	const simulateAIThinking = async (searchQuery: string): Promise<CommandSuggestion[]> => {
		isThinking = true;
		
		// Simulate AI processing time
		await new Promise(resolve => setTimeout(resolve, 800 + Math.random() * 400));
		
		// Filter and score commands based on query
		const filtered = defaultCommands
			.filter(cmd => 
				cmd.command.toLowerCase().includes(searchQuery.toLowerCase()) ||
				cmd.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
				cmd.category.toLowerCase().includes(searchQuery.toLowerCase())
			)
			.map(cmd => ({
				...cmd,
				confidence: Math.min(0.98, cmd.confidence + Math.random() * 0.1)
			}))
			.sort((a, b) => b.confidence - a.confidence)
			.slice(0, maxSuggestions);

		isThinking = false;
		return filtered;
	};

	// Update suggestions based on query
	const updateSuggestions = async (newQuery: string) => {
		if (!newQuery.trim()) {
			aiSuggestions.set([]);
			return;
		}

		if (aiMode) {
			const results = await simulateAIThinking(newQuery);
			aiSuggestions.set(results);
		} else {
			const filtered = suggestions.slice(0, maxSuggestions);
			aiSuggestions.set(filtered);
		}
	};

	// Handle keyboard navigation
	const handleKeydown = (event: KeyboardEvent) => {
		const currentSuggestions = $aiSuggestions;
		
		switch (event.key) {
			case 'ArrowDown':
				event.preventDefault();
				selectedIndex = Math.min(selectedIndex + 1, currentSuggestions.length - 1);
				break;
			case 'ArrowUp':
				event.preventDefault();
				selectedIndex = Math.max(selectedIndex - 1, -1);
				break;
			case 'Enter':
				event.preventDefault();
				if (selectedIndex >= 0 && currentSuggestions[selectedIndex]) {
					selectCommand(currentSuggestions[selectedIndex]);
				}
				break;
			case 'Escape':
				selectedIndex = -1;
				aiSuggestions.set([]);
				break;
		}
	};

	// Select a command
	const selectCommand = (command: CommandSuggestion) => {
		dispatch('select', {
			command,
			timestamp: new Date()
		});
		selectedIndex = -1;
	};

	// Get confidence color
	const getConfidenceColor = (confidence: number): string => {
		if (confidence >= 0.9) return 'text-green-400';
		if (confidence >= 0.7) return 'text-yellow-400';
		if (confidence >= 0.5) return 'text-orange-400';
		return 'text-red-400';
	};

	// Get confidence label
	const getConfidenceLabel = (confidence: number): string => {
		if (confidence >= 0.9) return 'HIGH';
		if (confidence >= 0.7) return 'MED';
		return 'LOW';
	};

	// React to query changes
	$effect(() => {
		updateSuggestions(query);
	});

	onMount(() => {
		// Add keyboard event listener
		window.addEventListener('keydown', handleKeydown);
		
		return () => {
			window.removeEventListener('keydown', handleKeydown);
		};
	});
</script>

{#if query.trim() && ($aiSuggestions.length > 0 || isThinking)}
	<div 
		class={cn(
			'relative mt-2 p-4 rounded-lg border backdrop-blur-md',
			'shadow-2xl transform-gpu',
			currentTheme.bg,
			className
		)}
		transition:fly={{ y: 10, duration: 200 }}
	>
		<!-- Header -->
		<div class={cn('flex items-center justify-between mb-3 pb-2 border-b border-current/20', currentTheme.text)}>
			<div class="flex items-center gap-2">
				<span class="text-sm font-bold">🤖 AI SUGGESTIONS</span>
				{#if isThinking}
					<div class="flex gap-1">
						<div class="w-1 h-1 bg-current rounded-full animate-bounce" style="animation-delay: 0ms;"></div>
						<div class="w-1 h-1 bg-current rounded-full animate-bounce" style="animation-delay: 150ms;"></div>
						<div class="w-1 h-1 bg-current rounded-full animate-bounce" style="animation-delay: 300ms;"></div>
					</div>
				{/if}
			</div>
			<span class={cn('text-xs', currentTheme.muted)}>
				{$aiSuggestions.length} matches
			</span>
		</div>

		<!-- Thinking State -->
		{#if isThinking}
			<div class={cn('flex items-center gap-3 p-3 rounded-lg bg-black/20', currentTheme.muted)}>
				<div class="w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin"></div>
				<span class="text-sm font-mono">Analyzing patterns...</span>
			</div>
		{/if}

		<!-- Suggestions List -->
		{#if !isThinking && $aiSuggestions.length > 0}
			<div class="space-y-2">
				{#each $aiSuggestions as suggestion, index}
					<div 
						class={cn(
							'p-3 rounded-lg cursor-pointer transition-all duration-200',
							'hover:scale-[1.02] transform-gpu border border-transparent',
							index === selectedIndex ? currentTheme.selected : 'hover:bg-white/5',
							'group'
						)}
						onclick={() => selectCommand(suggestion)}
						transition:fade={{ duration: 150, delay: index * 50 }}
					>
						<!-- Command Header -->
						<div class="flex items-center justify-between mb-2">
							<div class="flex items-center gap-2">
								{#if showCategories}
									<span class={categoryConfig[suggestion.category].color}>
										{categoryConfig[suggestion.category].icon}
									</span>
								{/if}
								<span class={cn('font-mono font-bold', currentTheme.text)}>
									{suggestion.command}
								</span>
							</div>
							
							{#if showConfidence}
								<div class="flex items-center gap-2">
									<span class={cn('text-xs font-bold', getConfidenceColor(suggestion.confidence))}>
										{getConfidenceLabel(suggestion.confidence)}
									</span>
									<div class="w-12 h-1.5 bg-gray-700 rounded-full overflow-hidden">
										<div 
											class={cn('h-full rounded-full transition-all duration-300', getConfidenceColor(suggestion.confidence).replace('text-', 'bg-'))}
											style="width: {suggestion.confidence * 100}%"
										></div>
									</div>
								</div>
							{/if}
						</div>

						<!-- Description -->
						<p class={cn('text-sm mb-2', currentTheme.muted)}>
							{suggestion.description}
						</p>

						<!-- Usage -->
						<div class={cn('text-xs font-mono p-2 rounded bg-black/30', currentTheme.accent)}>
							{suggestion.usage}
						</div>

						<!-- Examples (shown on hover) -->
						{#if suggestion.examples && suggestion.examples.length > 0}
							<div class="mt-2 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
								<div class={cn('text-xs font-bold mb-1', currentTheme.text)}>Examples:</div>
								<div class="flex flex-wrap gap-1">
									{#each suggestion.examples as example}
										<code class={cn('text-xs px-2 py-1 rounded bg-black/40', currentTheme.muted)}>
											{example}
										</code>
									{/each}
								</div>
							</div>
						{/if}
					</div>
				{/each}
			</div>
		{/if}

		<!-- No Results -->
		{#if !isThinking && query.trim() && $aiSuggestions.length === 0}
			<div class={cn('text-center py-8', currentTheme.muted)}>
				<div class="text-2xl mb-2">🤔</div>
				<p class="text-sm">No suggestions found for "{query}"</p>
				<p class="text-xs mt-1">Try a different search term</p>
			</div>
		{/if}

		<!-- Footer -->
		{#if !isThinking && $aiSuggestions.length > 0}
			<div class={cn('mt-3 pt-2 border-t border-current/20 text-xs', currentTheme.muted)}>
				<div class="flex items-center justify-between">
					<span>Use ↑↓ to navigate, Enter to select</span>
					<span>AI-powered suggestions</span>
				</div>
			</div>
		{/if}
	</div>
{/if}

<style>
	/* Smooth animations */
	.group:hover .group-hover\:opacity-100 {
		opacity: 1;
	}
</style>

// components/terminal/ai-command-suggestions.tsx
'use client';

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Zap, Sparkles, Brain, ArrowRight, Command } from 'lucide-react';
import { cn } from '../../lib/utils';

interface CommandSuggestion {
  command: string;
  description: string;
  category: 'system' | 'git' | 'npm' | 'docker' | 'custom';
  confidence: number;
  reasoning?: string;
}

interface AICommandSuggestionsProps {
  input: string;
  onSelect: (command: string) => void;
  selectedIndex?: number;
  onSelectedIndexChange?: (index: number) => void;
  className?: string;
  maxSuggestions?: number;
  showReasoningOnHover?: boolean;
}

const categoryConfig = {
  system: {
    icon: Command,
    color: 'text-blue-400',
    bgColor: 'bg-blue-400/20',
    borderColor: 'border-blue-400/30'
  },
  git: {
    icon: Zap,
    color: 'text-orange-400',
    bgColor: 'bg-orange-400/20',
    borderColor: 'border-orange-400/30'
  },
  npm: {
    icon: Sparkles,
    color: 'text-red-400',
    bgColor: 'bg-red-400/20',
    borderColor: 'border-red-400/30'
  },
  docker: {
    icon: Brain,
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-400/20',
    borderColor: 'border-cyan-400/30'
  },
  custom: {
    icon: ArrowRight,
    color: 'text-emerald-400',
    bgColor: 'bg-emerald-400/20',
    borderColor: 'border-emerald-400/30'
  }
};

const suggestionVariants = {
  hidden: { 
    opacity: 0, 
    y: 10, 
    scale: 0.95 
  },
  visible: { 
    opacity: 1, 
    y: 0, 
    scale: 1,
    transition: {
      type: 'spring',
      stiffness: 300,
      damping: 20
    }
  },
  exit: { 
    opacity: 0, 
    y: -10, 
    scale: 0.95,
    transition: { duration: 0.15 }
  }
};

const itemVariants = {
  idle: { 
    scale: 1, 
    x: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.05)'
  },
  hover: { 
    scale: 1.02, 
    x: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    transition: { duration: 0.15 }
  },
  selected: {
    scale: 1.02,
    x: 8,
    backgroundColor: 'rgba(0, 212, 170, 0.15)',
    borderColor: 'rgba(0, 212, 170, 0.4)',
    transition: { duration: 0.15 }
  }
};

// Mock AI suggestion generator - in production, this would connect to an AI service
const generateSuggestions = (input: string): CommandSuggestion[] => {
  const allSuggestions: CommandSuggestion[] = [
    {
      command: 'npm install',
      description: 'Install package dependencies',
      category: 'npm',
      confidence: 0.95,
      reasoning: 'Common NPM command for installing dependencies'
    },
    {
      command: 'git status',
      description: 'Check repository status',
      category: 'git',
      confidence: 0.9,
      reasoning: 'Shows current state of git repository'
    },
    {
      command: 'yarn dev',
      description: 'Start development server',
      category: 'npm',
      confidence: 0.85,
      reasoning: 'Commonly used to start development mode'
    },
    {
      command: 'docker ps',
      description: 'List running containers',
      category: 'docker',
      confidence: 0.8,
      reasoning: 'Shows active Docker containers'
    },
    {
      command: 'ls -la',
      description: 'List files with details',
      category: 'system',
      confidence: 0.9,
      reasoning: 'Display detailed file listing'
    },
    {
      command: 'git commit -m ""',
      description: 'Commit changes with message',
      category: 'git',
      confidence: 0.87,
      reasoning: 'Standard git commit with message'
    },
    {
      command: 'npm run build',
      description: 'Build production bundle',
      category: 'npm',
      confidence: 0.83,
      reasoning: 'Create optimized production build'
    },
    {
      command: 'code .',
      description: 'Open current directory in VS Code',
      category: 'system',
      confidence: 0.75,
      reasoning: 'Launch VS Code in current directory'
    },
    {
      command: 'git push origin main',
      description: 'Push to main branch',
      category: 'git',
      confidence: 0.82,
      reasoning: 'Push local commits to remote main branch'
    },
    {
      command: 'curl -X GET',
      description: 'Make HTTP GET request',
      category: 'system',
      confidence: 0.7,
      reasoning: 'Perform HTTP request using curl'
    }
  ];

  if (!input.trim()) return [];

  return allSuggestions
    .filter(suggestion => 
      suggestion.command.toLowerCase().includes(input.toLowerCase()) ||
      suggestion.description.toLowerCase().includes(input.toLowerCase())
    )
    .sort((a, b) => b.confidence - a.confidence)
    .slice(0, 6);
};

export function AICommandSuggestions({
  input,
  onSelect,
  selectedIndex = -1,
  onSelectedIndexChange,
  className,
  maxSuggestions = 6,
  showReasoningOnHover = true
}: AICommandSuggestionsProps) {
  const [suggestions, setSuggestions] = useState<CommandSuggestion[]>([]);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [hoveredIndex, setHoveredIndex] = useState(-1);

  useEffect(() => {
    if (!input.trim()) {
      setSuggestions([]);
      return;
    }

    setIsAnalyzing(true);
    // Simulate AI processing delay
    const timer = setTimeout(() => {
      const newSuggestions = generateSuggestions(input).slice(0, maxSuggestions);
      setSuggestions(newSuggestions);
      setIsAnalyzing(false);
    }, 150);

    return () => clearTimeout(timer);
  }, [input, maxSuggestions]);

  if (!input.trim() && !isAnalyzing) return null;

  return (
    <AnimatePresence>
      <motion.div
        variants={suggestionVariants}
        initial="hidden"
        animate="visible"
        exit="exit"
        className={cn(
          'p-4 rounded-xl bg-gradient-to-br from-emerald-500/10 via-blue-500/10 to-purple-500/10 border border-emerald-500/20 backdrop-blur-md',
          className
        )}
      >
        {/* Header */}
        <div className="flex items-center gap-3 mb-3">
          <motion.div
            animate={isAnalyzing ? { rotate: 360 } : {}}
            transition={{ duration: 1, repeat: isAnalyzing ? Infinity : 0, ease: 'linear' }}
            className="p-2 rounded-full bg-emerald-500/20"
          >
            <Brain className="w-4 h-4 text-emerald-400" />
          </motion.div>
          <div>
            <h3 className="text-emerald-400 font-bold text-sm flex items-center gap-2">
              <Sparkles className="w-3 h-3" />
              AI Command Intelligence
            </h3>
            <p className="text-white/60 text-xs">
              {isAnalyzing ? 'Analyzing patterns...' : `${suggestions.length} suggestions found`}
            </p>
          </div>
        </div>

        {/* Loading State */}
        {isAnalyzing && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="space-y-2"
          >
            {[...Array(3)].map((_, i) => (
              <motion.div
                key={i}
                animate={{ opacity: [0.3, 0.7, 0.3] }}
                transition={{ duration: 1.5, repeat: Infinity, delay: i * 0.2 }}
                className="h-10 bg-white/10 rounded-lg"
              />
            ))}
          </motion.div>
        )}

        {/* Suggestions List */}
        {!isAnalyzing && suggestions.length > 0 && (
          <motion.div 
            className="space-y-2"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.1 }}
          >
            {suggestions.map((suggestion, index) => {
              const config = categoryConfig[suggestion.category];
              const CategoryIcon = config.icon;
              const isSelected = index === selectedIndex;
              const isHovered = index === hoveredIndex;

              return (
                <motion.button
                  key={suggestion.command + index}
                  variants={itemVariants}
                  animate={isSelected ? 'selected' : isHovered ? 'hover' : 'idle'}
                  onClick={() => onSelect(suggestion.command)}
                  onMouseEnter={() => {
                    setHoveredIndex(index);
                    onSelectedIndexChange?.(index);
                  }}
                  onMouseLeave={() => setHoveredIndex(-1)}
                  className={cn(
                    'w-full text-left p-3 rounded-lg border border-white/10 transition-all duration-150 group',
                    isSelected && 'border-emerald-500/30 bg-emerald-500/15'
                  )}
                >
                  <div className="flex items-center gap-3">
                    <motion.div
                      className={cn('p-1.5 rounded-md', config.bgColor)}
                      whileHover={{ scale: 1.1 }}
                    >
                      <CategoryIcon className={cn('w-3 h-3', config.color)} />
                    </motion.div>
                    
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <code className="text-white/90 font-semibold text-sm">
                          {suggestion.command}
                        </code>
                        <motion.div
                          initial={{ scale: 0 }}
                          animate={{ scale: suggestion.confidence }}
                          className="w-12 h-1 bg-emerald-400/30 rounded-full overflow-hidden"
                        >
                          <motion.div
                            initial={{ width: 0 }}
                            animate={{ width: `${suggestion.confidence * 100}%` }}
                            transition={{ delay: 0.2, duration: 0.5 }}
                            className="h-full bg-emerald-400 rounded-full"
                          />
                        </motion.div>
                      </div>
                      <p className="text-white/60 text-xs">{suggestion.description}</p>
                    </div>

                    <ArrowRight className="w-4 h-4 text-white/40 group-hover:text-emerald-400 transition-colors" />
                  </div>

                  {/* Reasoning Tooltip */}
                  {showReasoningOnHover && suggestion.reasoning && isHovered && (
                    <motion.div
                      initial={{ opacity: 0, y: 5 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="mt-2 p-2 rounded-md bg-black/40 border border-white/10"
                    >
                      <p className="text-white/70 text-xs italic">
                        💡 {suggestion.reasoning}
                      </p>
                    </motion.div>
                  )}
                </motion.button>
              );
            })}
          </motion.div>
        )}

        {/* No Results */}
        {!isAnalyzing && suggestions.length === 0 && input.trim() && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="text-center py-4"
          >
            <p className="text-white/50 text-sm">
              No suggestions found for "{input}"
            </p>
            <p className="text-white/30 text-xs mt-1">
              Try a different command or continue typing
            </p>
          </motion.div>
        )}

        {/* AI Branding */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 0.6 }}
          transition={{ delay: 0.5 }}
          className="mt-3 pt-2 border-t border-white/10 flex items-center justify-center gap-1 text-xs text-white/40"
        >
          <Sparkles className="w-3 h-3" />
          <span>Powered by Liquid AI</span>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}
