// glass-ui/src/components/input.tsx
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../utils/cn';

const inputVariants = cva(
  'flex w-full rounded-md text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 transition-all duration-200',
  {
    variants: {
      variant: {
        default: 'h-10 border border-input bg-background px-3 py-2',
        filled: 'h-10 bg-white/10 border border-white/20 backdrop-blur-md px-3 py-2 hover:bg-white/20',
        outline: 'h-10 border-2 border-input bg-transparent px-3 py-2 focus:border-primary',
        ghost: 'h-10 bg-transparent border-none px-3 py-2 hover:bg-white/5',
        glass: 'h-10 bg-white/5 border border-white/20 backdrop-blur-md px-3 py-2 shadow-lg',
        'glass-dark': 'h-10 bg-black/5 border border-black/20 backdrop-blur-md px-3 py-2 shadow-lg',
      },
      inputSize: {
        default: 'h-10',
        sm: 'h-9 text-xs',
        lg: 'h-12 text-base',
      },
    },
    defaultVariants: {
      variant: 'default',
      inputSize: 'default',
    },
  }
);

export interface InputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size'>,
    VariantProps<typeof inputVariants> {}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, variant, inputSize, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(inputVariants({ variant, inputSize, className }))}
        ref={ref}
        {...props}
      />
    );
  }
);
Input.displayName = 'Input';

export { Input, inputVariants };

// svelte-version/src/lib/components/Input.svelte
<script lang="ts">
  import { cn } from '$lib/utils.js';
  import type { HTMLInputAttributes } from 'svelte/elements';

  interface Props extends HTMLInputAttributes {
    variant?: 'default' | 'glass' | 'terminal';
    size?: 'sm' | 'md' | 'lg';
    label?: string;
    error?: string;
    icon?: any;
    children?: any;
    class?: string;
  }

  let {
    variant = 'default',
    size = 'md',
    label = '',
    error = '',
    icon = null,
    class: className = '',
    id = '',
    children,
    ...restProps
  }: Props = $props();

  const variants = {
    default: 'bg-white/5 border border-white/20 focus:border-brand-primary',
    glass: 'glass border-white/30 focus:border-terminal-green/50 focus:shadow-lg',
    terminal: 'bg-terminal-bg border border-terminal-green/20 focus:border-terminal-green text-terminal-fg font-mono'
  };

  const sizes = {
    sm: 'px-3 py-1.5 text-sm',
    md: 'px-4 py-2 text-base',
    lg: 'px-5 py-3 text-lg'
  };

  const baseClasses = 'w-full rounded-brand outline-none transition-all duration-moderate placeholder:text-white/40';
  const errorClasses = error ? 'border-red-500 focus:border-red-500' : '';
  const iconClasses = (icon || children?.icon) ? 'pl-10' : '';
  
  const combinedClasses = cn(
    baseClasses,
    variants[variant],
    sizes[size],
    errorClasses,
    iconClasses,
    className
  );

  const uniqueId = id || `input-${Math.random().toString(36).substr(2, 9)}`;
</script>

<div class="relative">
  {#if label}
    <label for={uniqueId} class="block text-sm font-medium text-white/80 mb-2">
      {label}
    </label>
  {/if}
  
  <div class="relative">
    {#if icon}
      <div class="absolute left-3 top-1/2 -translate-y-1/2 text-white/40">
        {@render icon()}
      </div>
    {:else if children?.icon}
      <div class="absolute left-3 top-1/2 -translate-y-1/2 text-white/40">
        {@render children.icon()}
      </div>
    {/if}
    
    <input 
      {id}
      class={combinedClasses}
      {...restProps}
    />
  </div>
  
  {#if error}
    <p class="mt-1 text-sm text-red-400" role="alert">
      {error}
    </p>
  {/if}
</div>

<style>
  input:focus {
    box-shadow: 0 0 0 3px rgba(0, 122, 255, 0.1);
  }
  
  input.glass:focus {
    backdrop-filter: blur(16px) saturate(200%);
  }
  
  input.terminal {
    caret-color: var(--terminal-green);
  }
</style>
