// svelte-version/src/lib/components/Badge.svelte
<script lang="ts">
	import { cn } from '$lib/utils.js';
	import { liquidBlur, glassFade } from '$lib/motion';
	import { sizeOf } from '$lib/utils/bundle-size.js';
	import type { HTMLAttributes } from 'svelte/elements';

	interface Props extends HTMLAttributes<HTMLSpanElement> {
		variant?: 'default' | 'primary' | 'secondary' | 'accent' | 'success' | 'warning' | 'error';
		size?: 'sm' | 'md' | 'lg';
		glass?: boolean;
		blur?: 'sm' | 'md' | 'lg' | 'xl';
		interactive?: boolean;
		animate?: boolean;
		reduceMotion?: boolean;
		class?: string;
		children?: any;
	}

	let {
		variant = 'default',
		size = 'md',
		glass = true,
		blur = 'md',
		interactive = false,
		animate = true,
		reduceMotion = false,
		class: className = '',
		children,
		...restProps
	}: Props = $props();

	const variants = {
		default: 'bg-white/10 text-white border-white/20',
		primary: 'bg-blue-500/20 text-blue-300 border-blue-400/30',
		secondary: 'bg-purple-500/20 text-purple-300 border-purple-400/30',
		accent: 'bg-red-500/20 text-red-300 border-red-400/30',
		success: 'bg-green-500/20 text-green-300 border-green-400/30',
		warning: 'bg-yellow-500/20 text-yellow-300 border-yellow-400/30',
		error: 'bg-red-600/20 text-red-300 border-red-500/30'
	};

	const sizes = {
		sm: 'px-2 py-1 text-xs font-medium',
		md: 'px-3 py-1.5 text-sm font-medium',
		lg: 'px-4 py-2 text-base font-medium'
	};

	const blurLevels = {
		sm: 'backdrop-blur-sm',
		md: 'backdrop-blur-md',
		lg: 'backdrop-blur-lg',
		xl: 'backdrop-blur-xl'
	};

	const baseClasses = 'inline-flex items-center justify-center rounded-full border transition-all duration-200';
	const glassClasses = glass ? `glass-subtle ${blurLevels[blur]}` : '';
	const interactiveClasses = interactive
		? 'cursor-pointer hover:scale-105 focus:outline-none focus:ring-2 focus:ring-white/30 focus:ring-offset-2 focus:ring-offset-transparent'
		: '';

	const combinedClasses = cn(baseClasses, variants[variant], sizes[size], glassClasses, interactiveClasses, className);

	function handleKeydown(event: KeyboardEvent) {
		if (interactive && (event.key === 'Enter' || event.key === ' ')) {
			event.preventDefault();
			event.currentTarget.dispatchEvent(new CustomEvent('click', { bubbles: true }));
		}
	}

	// Track bundle size
	$effect(() => {
		sizeOf('Badge', 'small');
	});
</script>

{#if animate && !reduceMotion}
	{#if interactive}
		<span
			class={combinedClasses}
			role="button"
			tabindex="0"
			aria-label={restProps['aria-label'] || `${variant} badge`}
			on:keydown={handleKeydown}
			use:liquidBlur={{ blur: blur, opacity: 'subtle' }}
			{...restProps}
		>
			{#if children}
				{@render children()}
			{/if}
		</span>
	{:else}
		<span
			class={combinedClasses}
			role="status"
			aria-label={restProps['aria-label'] || `${variant} badge`}
			in:glassFade={{ direction: 'up', distance: 10 }}
			{...restProps}
		>
			{#if children}
				{@render children()}
			{/if}
		</span>
	{/if}
{:else}
	<span
		class={combinedClasses}
		role={interactive ? 'button' : 'status'}
		tabindex={interactive ? 0 : undefined}
		aria-label={restProps['aria-label'] || `${variant} badge`}
		on:keydown={interactive ? handleKeydown : undefined}
		{...restProps}
	>
		{#if children}
			{@render children()}
		{/if}
	</span>
{/if}

<style>
	span[role='button'] {
		will-change: transform;
	}

	@media (prefers-reduced-motion: reduce) {
		span {
			transition: none;
			animation: none;
		}
	}
</style>

// glass-ui/src/components/badge.tsx
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../utils/cn';

const badgeVariants = cva(
  'inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
  {
    variants: {
      variant: {
        default: 'border-transparent bg-primary text-primary-foreground shadow hover:bg-primary/80',
        secondary: 'border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80',
        destructive: 'border-transparent bg-destructive text-destructive-foreground shadow hover:bg-destructive/80',
        outline: 'border border-input text-foreground',
        glass: 'bg-white/10 text-foreground border border-white/20 backdrop-blur-md shadow-lg',
        'glass-dark': 'bg-black/10 text-foreground border border-black/20 backdrop-blur-md shadow-lg',
        success: 'border-transparent bg-green-500 text-white shadow hover:bg-green-600',
        warning: 'border-transparent bg-yellow-500 text-black shadow hover:bg-yellow-600',
        info: 'border-transparent bg-blue-500 text-white shadow hover:bg-blue-600',
      },
      size: {
        default: 'h-6 px-2.5 text-xs',
        sm: 'h-5 px-2 text-xs',
        lg: 'h-7 px-3 text-sm',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  }
);

export interface BadgeProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof badgeVariants> {}

function Badge({ className, variant, size, ...props }: BadgeProps) {
  return (
    <div className={cn(badgeVariants({ variant, size }), className)} {...props} />
  );
}

export { Badge, badgeVariants };
