// svelte-version/src/lib/components/Switch.svelte
<script lang="ts">
	import { cn } from '$lib/utils.js';
	import { liquidBlur, springPop } from '$lib/motion';
	import { sizeOf } from '$lib/utils/bundle-size.js';
	import type { HTMLAttributes } from 'svelte/elements';

	interface Props extends Omit<HTMLAttributes<HTMLButtonElement>, 'value'> {
		checked?: boolean;
		disabled?: boolean;
		size?: 'sm' | 'md' | 'lg';
		variant?: 'default' | 'glass' | 'terminal';
		blur?: 'sm' | 'md' | 'lg' | 'xl';
		animate?: boolean;
		reduceMotion?: boolean;
		label?: string;
		description?: string;
		class?: string;
		onCheckedChange?: (checked: boolean) => void;
	}

	let {
		checked = false,
		disabled = false,
		size = 'md',
		variant = 'glass',
		blur = 'md',
		animate = true,
		reduceMotion = false,
		label,
		description,
		class: className = '',
		onCheckedChange,
		...restProps
	}: Props = $props();

	let switchElement: HTMLButtonElement;

	const sizes = {
		sm: {
			track: 'w-8 h-4',
			thumb: 'w-3 h-3',
			translate: 'translate-x-4'
		},
		md: {
			track: 'w-11 h-6',
			thumb: 'w-5 h-5',
			translate: 'translate-x-5'
		},
		lg: {
			track: 'w-14 h-8',
			thumb: 'w-6 h-6',
			translate: 'translate-x-6'
		}
	};

	const variants = {
		default: {
			track: 'bg-white/10 border border-white/20',
			trackChecked: 'bg-blue-500/30 border-blue-400/40',
			thumb: 'bg-white shadow-lg'
		},
		glass: {
			track: 'glass-subtle border border-white/20',
			trackChecked: 'glass-medium border-blue-400/40 bg-blue-500/20',
			thumb: 'bg-white/90 backdrop-blur-sm shadow-lg'
		},
		terminal: {
			track: 'bg-terminal-green/20 border border-terminal-green/40',
			trackChecked: 'bg-terminal-green/40 border-terminal-green/60',
			thumb: 'bg-terminal-green shadow-lg'
		}
	};

	const blurLevels = {
		sm: 'backdrop-blur-sm',
		md: 'backdrop-blur-md',
		lg: 'backdrop-blur-lg',
		xl: 'backdrop-blur-xl'
	};

	const trackClasses = cn(
		'relative inline-flex items-center rounded-full transition-all duration-200',
		'focus:outline-none focus:ring-2 focus:ring-blue-400/50 focus:ring-offset-2 focus:ring-offset-transparent',
		sizes[size].track,
		checked ? variants[variant].trackChecked : variants[variant].track,
		variant === 'glass' && blurLevels[blur],
		disabled && 'opacity-50 cursor-not-allowed',
		!disabled && 'cursor-pointer hover:scale-105',
		className
	);

	const thumbClasses = cn(
		'inline-block rounded-full transition-all duration-200 ease-in-out transform',
		sizes[size].thumb,
		variants[variant].thumb,
		checked ? sizes[size].translate : 'translate-x-0.5',
		!reduceMotion && 'will-change-transform'
	);

	function handleClick() {
		if (disabled) return;

		const newChecked = !checked;
		checked = newChecked;
		onCheckedChange?.(newChecked);
	}

	function handleKeydown(event: KeyboardEvent) {
		if (disabled) return;

		if (event.key === 'Enter' || event.key === ' ') {
			event.preventDefault();
			handleClick();
		}
	}

	// Track bundle size
	$effect(() => {
		sizeOf('Switch', 'small');
	});
</script>

<div class="flex items-center gap-3">
	<button
		bind:this={switchElement}
		type="button"
		role="switch"
		aria-checked={checked}
		aria-describedby={description ? 'switch-description' : undefined}
		aria-label={label || restProps['aria-label'] || 'Toggle switch'}
		class={trackClasses}
		{disabled}
		use:springPop={animate && !reduceMotion ? { scale: 0.95, duration: 100 } : undefined}
		on:click={handleClick}
		on:keydown={handleKeydown}
		{...restProps}
	>
		<span class={thumbClasses}></span>
	</button>

	{#if label || description}
		<div class="flex flex-col">
			{#if label}
				<label
					class="text-sm font-medium text-white cursor-pointer"
					class:opacity-50={disabled}
					for={switchElement?.id}
					on:click={handleClick}
				>
					{label}
				</label>
			{/if}
			{#if description}
				<p id="switch-description" class="text-xs text-white/70" class:opacity-50={disabled}>
					{description}
				</p>
			{/if}
		</div>
	{/if}
</div>

<style>
	button[role='switch'] {
		will-change: transform;
	}

	button[role='switch'] span {
		will-change: transform;
	}

	@media (prefers-reduced-motion: reduce) {
		button,
		span {
			transition: none;
			animation: none;
			will-change: auto;
		}
	}
</style>

// glass-ui/src/components/switch.tsx
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../utils/cn';

const switchVariants = cva(
  'inline-flex shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 backdrop-blur-sm',
  {
    variants: {
      variant: {
        default: 'data-[state=checked]:bg-primary data-[state=unchecked]:bg-white/10 shadow-lg',
        glass: 'data-[state=checked]:bg-primary/80 data-[state=unchecked]:bg-white/10 backdrop-blur-md shadow-xl border-white/20',
        'glass-dark': 'data-[state=checked]:bg-primary/80 data-[state=unchecked]:bg-black/10 backdrop-blur-md shadow-xl border-black/20',
      },
      size: {
        sm: 'h-5 w-9',
        default: 'h-6 w-11',
        lg: 'h-7 w-13',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  }
);

const thumbVariants = cva(
  'pointer-events-none block rounded-full bg-background shadow-lg ring-0 transition-transform',
  {
    variants: {
      size: {
        sm: 'h-4 w-4 data-[state=checked]:translate-x-4 data-[state=unchecked]:translate-x-0',
        default: 'h-5 w-5 data-[state=checked]:translate-x-5 data-[state=unchecked]:translate-x-0',
        lg: 'h-6 w-6 data-[state=checked]:translate-x-6 data-[state=unchecked]:translate-x-0',
      },
    },
    defaultVariants: {
      size: 'default',
    },
  }
);

export interface SwitchProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size'>,
    VariantProps<typeof switchVariants> {
  label?: string;
  description?: string;
}

const Switch = React.forwardRef<HTMLInputElement, SwitchProps>(
  ({ className, variant, size, label, description, checked, ...props }, ref) => {
    const [isChecked, setIsChecked] = React.useState(checked || false);

    React.useEffect(() => {
      setIsChecked(checked || false);
    }, [checked]);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
      setIsChecked(e.target.checked);
      props.onChange?.(e);
    };

    const id = props.id || `switch-${Math.random().toString(36).substr(2, 9)}`;

    return (
      <div className="flex items-center space-x-3">
        <div className="relative">
          <input
            type="checkbox"
            ref={ref}
            id={id}
            checked={isChecked}
            onChange={handleChange}
            className="sr-only"
            {...props}
          />
          <label
            htmlFor={id}
            className={cn(
              switchVariants({ variant, size }),
              className
            )}
            data-state={isChecked ? 'checked' : 'unchecked'}
          >
            <span
              className={cn(thumbVariants({ size }))}
              data-state={isChecked ? 'checked' : 'unchecked'}
            />
          </label>
        </div>

        {(label || description) && (
          <div className="flex flex-col">
            {label && (
              <label
                htmlFor={id}
                className="text-sm font-medium text-foreground cursor-pointer"
              >
                {label}
              </label>
            )}
            {description && (
              <p className="text-xs text-muted-foreground mt-1">
                {description}
              </p>
            )}
          </div>
        )}
      </div>
    );
  }
);

Switch.displayName = 'Switch';

export { Switch, switchVariants, thumbVariants as switchThumbVariants };
